# Generated by Django 5.2.5 on 2025-11-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Full-Time", "Full-Time"),
                            ("Part-Time", "Part-Time"),
                            ("Remote", "Remote"),
                            ("Hybrid", "Hybrid"),
                            ("Contract", "Contract"),
                            ("Internship", "Internship"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=300)),
                ("salary", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Entry Level", "Entry Level"),
                            ("Mid Level", "Mid Level"),
                            ("Senior Level", "Senior Level"),
                        ],
                        max_length=20,
                    ),
                ),
                ("skill", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
    ]
