# Generated by Django 5.2.5 on 2026-06-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_applyjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefultToRealPRofile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_pic", models.FileField(upload_to="profile_pic/")),
            ],
        ),
    ]
