# Generated by Django 6.0.6 on 2026-06-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_applyjob_applied_date_applyjob_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
