# Generated by Django 6.0.6 on 2026-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_chatmessage_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="job_images/"),
        ),
    ]
